import React, { createContext, useState } from "react";

const translations = {
  en: {
    helloCoach: "Hello Coach",
    logout: "Logout",
    login: "Login",
    patientList: "Patient List",
    addNewPatient: "+ Add New Patient",
    searchPatients: "Search patients...",
    name: "Name",
    birthday: "Birthday",
    sex: "Sex",
    age: "Age",
    actions: "Actions",
    update: "Update",
    save: "Save",
    print: "Print",
    saveAsPDF: "Save as PDF",
    saveToDatabase: "Save to Database",
    cancel: "Cancel",
    submit: "Submit",
    prescriptions: "Prescriptions",
    createPrescription: "Create Prescription",
    loading: "Loading...",
    noPrescriptionsFound: "No prescriptions found.",
    date: "Date",
    coach: "Coach",
    content: "Content",
    copy: "Copy",
    addRecipe: "Add Recipe",
    edit: "Edit",
    delete: "Delete",
    searchRemedies: "Search remedies...",
    editRecipe: "Edit Recipe",
    source: "Source",
    instructions: "Instructions",
    notes: "Notes",
    add: "Add",
    patient: "Patient",
    recipe: "Recipe",
    paste: "Paste",
    welcomeBack: "Welcome Back",
    enterPasscodeToContinue: "Please enter your passcode to continue",
    enterYourPasscode: "Enter your passcode",
    invalidPasscode: "Invalid passcode. Please try again.",
    changePasscode: "Change Passcode",
    adminPasscode: "Admin passcode",
    currentPasscode: "Current passcode",
    newPasscode: "New passcode",
    confirmNewPasscode: "Confirm new passcode",
    saving: "Saving...",
    saveNewPasscode: "Save New Passcode",
    adminPassIncorrect: "Admin passcode is incorrect.",
    currentPassIncorrect: "Current passcode is incorrect.",
    newPassMinLength: "New passcode must be at least 4 characters.",
    newPassNoMatch: "New passcodes do not match.",
    passChanged: "Passcode changed successfully!",
    loginSuccess: "Login successful! Redirecting...",
    confirmDeletePrescription:
      "Are you sure you want to delete this prescription?",
    prescriptionDeleted: "Prescription deleted successfully!",
    failedToDeletePrescription: "Failed to delete prescription.",
    recipeAdded: "Recipe added successfully!",
    // ...add more as needed
  },
  de: {
    helloCoach: "Hallo Coach",
    logout: "Abmelden",
    login: "Anmelden",
    patientList: "Patientenliste",
    addNewPatient: "+ Neuer Patient",
    searchPatients: "Patienten suchen...",
    name: "Name",
    birthday: "Geburtstag",
    sex: "Geschlecht",
    age: "Alter",
    actions: "Aktionen",
    update: "Aktualisieren",
    save: "Speichern",
    print: "Drucken",
    saveAsPDF: "Als PDF speichern",
    saveToDatabase: "In Datenbank speichern",
    cancel: "Abbrechen",
    submit: "Absenden",
    prescriptions: "Rezepte",
    createPrescription: "Rezept erstellen",
    loading: "Lädt...",
    noPrescriptionsFound: "Keine Rezepte gefunden.",
    date: "Datum",
    coach: "Coach",
    content: "Inhalt",
    copy: "Kopieren",
    addRecipe: "Heilmittel hinzufügen",
    edit: "Bearbeiten",
    delete: "Löschen",
    searchRemedies: "Mittel suchen...",
    editRecipe: "Rezept bearbeiten",
    source: "Quelle",
    instructions: "Anleitung",
    notes: "Notizen",
    add: "Hinzufügen",
    patient: "Patient",
    recipe: "Rezept",
    paste: "Einfügen",
    welcomeBack: "Willkommen zurück",
    enterPasscodeToContinue:
      "Bitte geben Sie Ihren Zugangscode ein, um fortzufahren",
    enterYourPasscode: "Geben Sie Ihren Zugangscode ein",
    invalidPasscode: "Ungültiger Zugangscode. Bitte versuchen Sie es erneut.",
    changePasscode: "Passcode ändern",
    adminPasscode: "Admin-Passcode",
    currentPasscode: "Aktueller Passcode",
    newPasscode: "Neuer Passcode",
    confirmNewPasscode: "Neuen Passcode bestätigen",
    saving: "Speichern...",
    saveNewPasscode: "Neuen Passcode speichern",
    adminPassIncorrect: "Admin-Passcode ist falsch.",
    currentPassIncorrect: "Aktueller Passcode ist falsch.",
    newPassMinLength: "Neuer Passcode muss mindestens 4 Zeichen lang sein.",
    newPassNoMatch: "Neue Passcodes stimmen nicht überein.",
    passChanged: "Passcode erfolgreich geändert!",
    loginSuccess: "Anmeldung erfolgreich! Weiterleitung...",
    confirmDeletePrescription: "Möchten Sie dieses Rezept wirklich löschen?",
    prescriptionDeleted: "Rezept erfolgreich gelöscht!",
    failedToDeletePrescription: "Löschen des Rezepts fehlgeschlagen.",
    male: "Männlich",
    female: "Weiblich",
    other: "Divers",
    select: "Auswählen",
    recipeAdded: "Rezept erfolgreich hinzugefügt!",
    fillAllFields: "Bitte füllen Sie alle Felder aus.",
    failedToSavePrescription: "Speichern des Rezepts fehlgeschlagen.",
    // ...add more as needed
  },
};

const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [language, setLanguage] = useState("de");
  const t = translations[language];
  return (
    <LangContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LangContext.Provider>
  );
};

export { LangContext };
